image: ubuntu
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true

branches:
  only:
    - master

environment:
  PS_GELLERY_RELEASE_API:
    secure: xBR5JNFYMUisp+oIx08EbfQ5xWsToa0XufJKuyaazeXy9wYcs6Fezw//NtW60uOF
  GITHUB_RELEASE_API:
    secure: s55znS9PHRv9SOXWiAmrxjj9c166WrBKTFz7cQmA0wLp9tGzREudX8XmaqbQH3YT

install:
  - export NETCORE_VERSION=2.2
  - sudo apt-get update && sudo apt-get install -y wget
  # libicu60
  - wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu60_60.2-6ubuntu1_amd64.deb
  - sudo dpkg -i libicu60_60.2-6ubuntu1_amd64.deb
  # .net core
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get -y install apt-transport-https
  - sudo apt-get update
  - sudo apt-get -y install dotnet-sdk-${NETCORE_VERSION}
  # pwsh
  - export PS_VERSION=6.1.0
  - export PS_PACKAGE=powershell_${PS_VERSION}-1.ubuntu.18.04_amd64.deb
  - export PS_PACKAGE_URL=https://github.com/PowerShell/PowerShell/releases/download/v${PS_VERSION}/${PS_PACKAGE}
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update && sudo apt-get install -y powershell
  - pwsh --version
  - pwsh -c Install-Module Pester -Scope CurrentUser -Force

build: off

build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - pwsh -file ./run_build.ps1 -Version ${APPVEYOR_BUILD_VERSION}
  - 7z a ./publish/Utf8BomHeader/ ./publish/publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip

test_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - pwsh -c Invoke-Pester

deploy:
  release: ${APPVEYOR_REPO_TAG_NAME}
  description: "${APPVEYOR_REPO_TAG_NAME} Release"
  provider: GitHub
  auth_token:
    secure: ${GITHUB_RELEASE_API}
  artifact: ./publish/publish/Utf8BomHeader_${APPVEYOR_REPO_TAG_NAME}.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

artifacts:
  - path: ./publish/publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip
    name: Utf8BomHeader_${APPVEYOR_BUILD_VERSION}