image: Ubuntu1804
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true

branches:
  only:
    - master

environment:
  PS_GELLERY_RELEASE_API:
    secure: xBR5JNFYMUisp+oIx08EbfQ5xWsToa0XufJKuyaazeXy9wYcs6Fezw//NtW60uOF
  GITHUB_RELEASE_API:
    secure: s55znS9PHRv9SOXWiAmrxjj9c166WrBKTFz7cQmA0wLp9tGzREudX8XmaqbQH3YT
  GUID: 11da18bb-f0d4-4509-b709-8b17efd8bb17
  DEPLOY_TRIGGER_BRANCH: master

install:
  - pwsh --version
  - pwsh -c Install-Module Pester -Scope CurrentUser -Force

build: off

build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - pwsh -file ./run_build.ps1 -Version ${APPVEYOR_BUILD_VERSION}
  - 7z a ./publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip ./publish/Utf8BomHeader/

test_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - pwsh -c "Invoke-Pester -OutputFormat NUnitXml -OutputFile ${APPVEYOR_BUILD_FOLDER}/TestResults.xml"
  - pwsh -c "(New-Object 'System.Net.WebClient').UploadFile('https://ci.appveyor.com/api/testresults/nunit/${APPVEYOR_JOB_ID}', '${APPVEYOR_BUILD_FOLDER}/TestResults.xml')"

deploy:
  release: ${APPVEYOR_REPO_TAG_NAME}
  description: "${APPVEYOR_REPO_TAG_NAME} Release"
  provider: GitHub
  auth_token:
    secure: ${GITHUB_RELEASE_API}
  artifact: ./publish/Utf8BomHeader_${APPVEYOR_REPO_TAG_NAME}.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: ${DEPLOY_TRIGGER_BRANCH}                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

deploy_script:
  - pwsh -file ./run_psgallery_deploy.ps1 -NuGetApiKey ${PS_GELLERY_RELEASE_API} -BuildBranch ${DEPLOY_TRIGGER_BRANCH}

artifacts:
  - path: ./publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip
    name: Utf8BomHeader_${APPVEYOR_BUILD_VERSION}

on_finish:
  - sh: |
      curl -F "file=${APPVEYOR_BUILD_FOLDER}/TestResults.xml" "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"