image: Ubuntu1804
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true
services:
- docker

branches:
  only:
    - master

environment:
  PS_GELLERY_RELEASE_API:
    secure: xBR5JNFYMUisp+oIx08EbfQ5xWsToa0XufJKuyaazeXy9wYcs6Fezw//NtW60uOF
  GITHUB_RELEASE_API:
    secure: s55znS9PHRv9SOXWiAmrxjj9c166WrBKTFz7cQmA0wLp9tGzREudX8XmaqbQH3YT
  GUID: 11da18bb-f0d4-4509-b709-8b17efd8bb17

install:
  - pwsh --version

before_build:
  - docker build -t utf8bomheader_build:latest .
  - docker image ls

build: off

build_script:
  - docker run --rm -v "${PWD}/publish:/app/publish" utf8bomheader_build:latest "./build_psd1.ps1 -Version ${APPVEYOR_BUILD_VERSION}"
  - 7z a ./publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip ./publish/Utf8BomHeader/

test_script:
  - docker run --rm utf8bomheader_build:latest "Invoke-Pester -CodeCoverage src/Utf8BomHeader.psm1"

deploy_script:
  - pwsh -file ./deploy_pagallery.ps1 -NuGetApiKey ${PS_GELLERY_RELEASE_API} -BuildBranch master -ModuleName Utf8BomHeader

artifacts:
  - path: ./publish/Utf8BomHeader_${APPVEYOR_BUILD_VERSION}.zip
    name: Utf8BomHeader_${APPVEYOR_BUILD_VERSION}
